export enum CreateFormSteps {
    Email = 'Email',
    Password = 'Password',
    Name = 'Name',
    Birthday = 'Birthday',
    Experience = 'Experience',
    ViewExperiences = 'ViewExperiences',
    Education = 'Education',
    ViewEducations = 'ViewEducations',
    Skills = 'Skilss',
    JobPreferences = 'JobPreferences',
    Perks = 'Perks',
    Notifications = 'Notifications',
    ProfilePhoto = 'ProfilePhoto',
    Done = 'Done',
}

export const skills = [
    'HTML',
    'CSS',
    'JavaScript',
    'Responsive Design',
    'GIT',
    'Web Performance Optimization',
    'React',
    'Next.js',
    'Tailwind',
    'Angular',
    'Vue.js',
    'Jest',
    'Testing Library',
    'Sass',
    'Less',
    'Redux',
    'MobX',
    'Figma',
    'Python',
    'Java',
    'Ruby',
    'PHP',
    'GraphQL',
    'Microservices',
    'CORS',
    'WebSockets',
    'Quarkus',
    'Node.js',
    'SQL',
    'NoSQL',
    'API Design',
    'Django',
    'Ruby on Rails',
    'RESTful APIs',
];

export const jobRoles = [
    'Software Engineer/Developer',
    'Frontend Developer',
    'Backend Developer',
    'Full-Stack Developer',
    'Mobile App Developer',
    'DevOps Engineer',
    'Quality Assurance/Testing Engineer',
    'UI/UX Designer',
    'Data Scientist',
    'Data Engineer',
    'Machine Learning Engineer',
    'Cloud Engineer',
    'Security Engineer',
    'Product Manager',
    'Project Manager',
    'Scrum Master',
    'Technical Architect',
    'Database Administrator (DBA)',
    'Software Development Manager',
    'Release Manager',
    'Site Reliability Engineer (SRE)',
    'Integration Engineer',
    'Support Engineer',
    'Automation Engineer',
    'Embedded Software Engineer',
];

export const jobLocations = [
    'On-Site/In-Office',
    'Hybrid',
    'Remote',
    'Freelancing/Contracting',
];

export const employmentTypes = [
    'Full-Time',
    'Part-Time',
    'Contract/Temporary',
    'Freelance/Gig',
    'Internship',
    'Consultant',
    'Volunteer',
];
